# Generated by Django 4.1.7 on 2023-03-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="activation_code",
            field=models.CharField(default="KPwox0lRCo", max_length=10),
        ),
    ]
