# Generated by Django 4.1.7 on 2023-03-08 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_rename_community_user_audience"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("competence", models.CharField(blank=True, max_length=255)),
                ("language", models.CharField(blank=True, max_length=2)),
                ("site_url", models.URLField(blank=True, max_length=255)),
                ("twitter_url", models.URLField(blank=True, max_length=255)),
                ("facebook_url", models.URLField(blank=True, max_length=255)),
                ("linkedin_url", models.URLField(blank=True, max_length=255)),
                ("youtube_url", models.URLField(blank=True, max_length=255)),
                ("image", models.ImageField(blank=True, upload_to="media/")),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_hidden_courses", models.BooleanField(default=False)),
                ("promotions", models.BooleanField(default=False)),
                ("mentor_ads", models.BooleanField(default=False)),
                ("email_ads", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
