# Generated by Django 4.1.7 on 2023-03-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activation_code_expiration",
            field=models.DateTimeField(null=True),
        ),
    ]
