# Generated by Django 4.1.7 on 2023-03-19 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_user_activation_code_expiration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="activation_code_expiration",
            new_name="activation_code_created_at",
        ),
    ]
