# Generated by Django 4.1.7 on 2023-03-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_remove_user_activation_code_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activation_code_created_at",
            field=models.DateTimeField(null=True),
        ),
    ]
