version: '3.8'

services:

  db:
    image: postgres:14.7
    container_name: db
    env_file:
      - .env
    
     
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: django
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 core.wsgi"
    ports:
      - "8000:8000"
    depends_on:
      - db 
      - redis
      - test


  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: nginx
    image: nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - app
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"



  test:
    build:
      context: .
    container_name: test
    env_file:
      - .env
    command: >
      sh -c "python manage.py test"
    depends_on:
      - db
   

  redis:
    image: redis:alpine
    hostname: redis

  celery:
    build:
      context: .
    command: celery -A core worker -l info
    volumes:
      - .:/app 
    env_file:
      - .env
    links:
      - redis
    depends_on:
      - db
      - redis
      - app
      - test

volumes:
  static_volume:
  media_volume:
